// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331023727_InitialCartSetup")]
    partial class InitialCartSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("api.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("api.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Textbooks",
                            Description = "Used textbook in good condition.",
                            ImageUrl = "/images/textbook1.jpg",
                            PostedDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 35m,
                            SellerName = "William Murdoch",
                            Title = "CSE 3241 Textbook"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            Description = "Works perfectly and fits most Dell laptops.",
                            ImageUrl = "/images/laptop1.jpg",
                            PostedDate = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 18m,
                            SellerName = "William Murdoch",
                            Title = "Laptop Charger"
                        },
                        new
                        {
                            Id = 3,
                            Category = "School Supplies",
                            Description = "Barely used, clean and ready for lab.",
                            ImageUrl = "/images/goggles1.jpg",
                            PostedDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 12m,
                            SellerName = "Maya Patel",
                            Title = "Biology Lab Goggles"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Textbooks",
                            Description = "Some highlighting but still in solid condition.",
                            ImageUrl = "/images/textbook2.jpg",
                            PostedDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 28m,
                            SellerName = "Maya Patel",
                            Title = "General Chemistry Textbook"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Furniture",
                            Description = "Works great, perfect for dorms or apartments.",
                            ImageUrl = "/images/fridge1.jpg",
                            PostedDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 80m,
                            SellerName = "Justin Westerling",
                            Title = "Mini Fridge"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Furniture",
                            Description = "Comfortable chair for studying or gaming.",
                            ImageUrl = "/images/chair1.jpg",
                            PostedDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 45m,
                            SellerName = "Justin Westerling",
                            Title = "Desk Chair"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Electronics",
                            Description = "Small apartment microwave in good working condition.",
                            ImageUrl = "/images/microwave1.jpg",
                            PostedDate = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30m,
                            SellerName = "Justin Westerling",
                            Title = "Microwave"
                        },
                        new
                        {
                            Id = 8,
                            Category = "School Supplies",
                            Description = "Five unused notebooks for classes.",
                            ImageUrl = "/images/notebooks1.jpg",
                            PostedDate = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 8m,
                            SellerName = "Maya Patel",
                            Title = "Notebook Pack"
                        });
                });

            modelBuilder.Entity("api.Models.CartItem", b =>
                {
                    b.HasOne("api.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("api.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("api.Models.Product", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
